### ISSUE TITLE
Add link to placement exam dates

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/CSUF-CPSC-handbooks#1]
They are found in a semester-specific "Registration Guide," e.g. http://www.fullerton.edu/admissions/currentstudent/guides/F2015.pdf

**Comment by mgofman** [comment]
To section 5.2 added the following:

> If you are eligible to take the exam, please see http://admissions.fullerton.edu/currentstudent/
> guides/F2016.pdf for exam dates, times, and locations.

**Comment by kevinwortman** [comment]
Thanks. I switched the link to the landing page for all semesters instead of Fall 2016 specifically.
