### ISSUE TITLE
move upper division GE to last two years

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/CSUF-CPSC-handbooks#13]
According to campus policy, upper division GE courses are only supposed to be taken by students with junior/senior standing. So our flowcharts should move the upper-division GE courses to those years.

**Comment by mgofman** [comment]
Do we have an editable flowchart file for this?  Or do we have to redraw it completely to fix this?

**Comment by kevinwortman** [comment]
The progress charts are generated procedurally in the latex source. By happenstance the upper division GE C.3 and D.1 were already in the third/fourth years. However we still need to move MATH 338 to the third/fourth year.

**Comment by kevinwortman** [comment]
It turns out that Michael and Sandra already fixed the 338 problem in their harmonized schedules. I propose copying their work. Michael, could you take a look at my comments in that Sheet regarding swapping 332 and 250A?

**Comment by kevinwortman** [comment]
Resolved by commit e08dbf6fbffc346491b53766cf30c3e387c95d5a .
