### ISSUE TITLE
hint about upper division GE

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/CSUF-CPSC-handbooks#14]
Add a hint saying that, effective Fall 2017, upper-division GE courses can only be taken by students at upper-division class standing.

See the "Implementation Plan to Bring CSUF into Full Compliance wit Title 5 and EO 1100.pdf" document for details.

**Comment by mgofman** [comment]
Added a tip on page 20:

"Effective Fall 2017, upper-division GE courses can only be taken by students at upper-division class standing."

**Comment by mshafae** [comment]
> On Jun 24, 2016, at 7:13 PM, mgofman notifications@github.com wrote:
> 
> Added a tip on page 20:
> 
> "Effective Fall 2017, upper-division GE courses can only be taken by students at upper-division class standing."
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Fall 2017 or fall 2016?

## Michael

Excuse the terseness; sent from a phone

**Comment by mgofman** [comment]
The comment said 2017.

Thanks,
Mikhail 

-----Original Message-----

**Comment by kevinwortman** [comment]
I double checked the memo and it says "The pre-requisites outlined above will be enforced beginning with the Fall 2017 semester.". So the current text is correct.
