### ISSUE TITLE
GE golden four grade requirement

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/CSUF-CPSC-handbooks#15]
Update the grade requirement table to reflect the "C-" requirement for the golden four GE areas.

**Comment by mgofman** [comment]
Changed the minimum grade requirement for GE categories A.1 and A.2 to C-.

The updated version has been pushed to Github.

**Comment by kevinwortman** [comment]
Thanks. I streamlined the table to group like requirements on contiguous rows.
