### ISSUE TITLE
Add guidance for students in the ROTC program

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/CSUF-CPSC-handbooks#2]

**Comment by kevinwortman** [comment]
See the "Report-to-UGC-re-ROTC.odt" document in the Undergraduate Committee folder in GDrive.

ROTC students have a higher unit limit (as many as 21 units), but a hard time to degree limit of 8 semesters. They should be advised to meet with a Department adviser ASAP to map this out. Also, we should provide one or two Progress Flowcharts that show how they can finish the major in 8 units, even with setbacks in the programming or math prerequisite chains, by exceeding the usual 16 unit limit.

**Comment by mgofman** [comment]
Added section 5.6 Computer Science Majors in the ROTC Program

> Computer Science majors intersted in joining the Reserve Officers’ Training Corps (ROTC) program should schedule a long appointment (30 minutes) with an advisor in their freshman year to map out the complete study plan. Prior to the meeting, the student must obtain the proper documents from ROTC office located in MS-101 (Military Science Building room 101) and bring those documents with them to the advising session.

No flowcharts have been added yet.

**Comment by kevinwortman** [comment]
Looks good. I shortened the section heading. Michael is working on a new round of flowcharts so let's call this settled.
