### ISSUE TITLE
Make all link URLs visible in hardcopy

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/CSUF-CPSC-handbooks#4]

**Comment by mgofman** [comment]
This URL is no longer valid. 
http://www.fullerton.edu/ecs/cs/resources/formsDocuments.asp

**Comment by mgofman** [comment]
Made all the links visible in the hardcopyh. Used bit.ly to shorten long and ugly URLS.

**Comment by mshafae** [comment]
> On Jun 24, 2016, at 8:41 PM, mgofman notifications@github.com wrote:
> 
> Made all the links visible in the hardcopyh. Used bit.ly to shorten long and ugly URLS.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> There is a problem using bit.ly which is that all URLs are permanent. I'm of the mind that we need a solution that is mshafae@fullerton.edu specific so we can have short URLs that are editable. 

Ex. http://csuf.org/cpsccatalog

## Michael

Excuse the terseness; sent from a phone

**Comment by mgofman** [comment]
That would be great!

Any suggestions on the solution?

Thanks,
Mikhail 

-----Original Message-----

**Comment by kevinwortman** [comment]
I noticed that some of the URLs were in a \url nested inside a \href which caused them to be drawn inside two nested boxes, which looked odd. I removed the nesting so now links are just inside a toplevel \url .

We still need a solution for editable redirects.

**Comment by scehrios2016** [comment]
I'm thinking of doing an in-house URL shortener. Any recommendations for a domain name?

**Comment by mshafae** [comment]
Sorry about the earlier comment. I was logged in under a different account.

I'm thinking about doing an in-house URL shortener. Any recommendations on a domain name? cscsuf and cpsccsuf are all available.

**Comment by kevinwortman** [comment]
Both domains sound good. I guess I prefer the cpsc abbreviation since it's more consistent with the student-facing registration system. Actually what about csufcpsc, just to avoid having the run of two cc's, which will be hard to pronounce?

**Comment by kevinwortman** [comment]
I converted all the URLs to use Michael's shrinker app in commit 27da17dcf348977ff9d4d21794911c0b7a0fcd74 . The domain name is in a macro so we can switch that easily.

**Comment by kevinwortman** [comment]
I switched the domain to csufcs.com in commit 9e369820d3a6034e6f81a9918e6446f32cd8d875 .
