### ISSUE TITLE
update the list of Free Electives

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/CSUF-CPSC-handbooks#6]
For example, 476 is missing.

**Comment by kevinwortman** [comment]
Also, use a different term because "Free Elective" is already a reserved word in the catalog.

**Comment by mgofman** [comment]
Updated the list of electives.

**Comment by kevinwortman** [comment]
Thanks. I further removed 303, 322L, 376, and 459 because they are slated for deletion.
