### ISSUE TITLE
feedback from Doina Bein

### ISSUE THREAD

**Issue by kevinwortman** [kevinwortman/CSUF-CPSC-handbooks#9]
Doina Bein suggests:

Top, page 9, it is mentioned “The Program Educational Objectives and Program Outcomes for the B.S. CS are documented in the University Catalog.”
But no link to the University Catalog is provided.

On page 9, second paragraph, it is mentioned “please refer to the Graduate Handbook instead of this document.” but no link is provided.

On page 15 bottom it is mentioned “The EPP is a prerequisite for several 300-level core courses as shown in the prerequisite tree in Section 3.2”
But EPP is not shown in the Figure only CPSC 301.

To the list on page 19, please add
CPSC 474 Distributed Computing

Missing period at the end of the paragraph in section 6.1 on page 31.

The word “surname” is misspelled (as “surnname”) on page 31, section 6.2

**Comment by mgofman** [comment]
> Top, page 9, it is mentioned “The Program Educational Objectives and Program Outcomes for the B.S. CS are documented in the University Catalog.”
> But no link to the University Catalog is provided.

There is already a link.

> On page 9, second paragraph, it is mentioned “please refer to the Graduate Handbook instead of this document.” but no link is provided.

Done.

> To the list on page 19, please add
> CPSC 474 Distributed Computing

Done.

> Missing period at the end of the paragraph in section 6.1 on page 31.

Done.

**Comment by mgofman** [comment]
On page 15 bottom it is mentioned “The EPP is a prerequisite for several 300-level core courses as shown in the prerequisite tree in Section 3.2”
But EPP is not shown in the Figure only CPSC 301.

This one still needs to be addressed.. I need the editable chart for this, as per previous comments.

**Comment by kevinwortman** [comment]
Looks good. The hand-drawn flowchart now shows 301 and EPP as alternatives.
